//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetStudent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetStudent()
        {
            this.Donations = new HashSet<Donation>();
        }
    
        public int Id { get; set; }
        public string StudentID { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string University { get; set; }
        public string Qualification { get; set; }
        public Nullable<System.DateTime> YearofStudy { get; set; }
        public Nullable<System.DateTime> YearofRequest { get; set; }
        public Nullable<int> AcademicAverage { get; set; }
        public Nullable<double> AmountofFundingNeeded { get; set; }
        public string WhatTheFundingWillBeUsedFor { get; set; }
        public string Bio { get; set; }
        public string Motivation { get; set; }
        public string CellNumber { get; set; }
        public Nullable<bool> CellNumberConfimed { get; set; }
        public string Email { get; set; }
        public Nullable<int> EmailConfirmed { get; set; }
        public byte[] Picture { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donation> Donations { get; set; }
    }
}
