//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonationCertificate
    {
        public int CertificateID { get; set; }
        public System.DateTime CertificateDate { get; set; }
        public int DonationID { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public string SendStatus { get; set; }
        public string CertificateReference { get; set; }
        public System.DateTime InsertDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Comment { get; set; }
        public string SentEmail { get; set; }
    
        public virtual Donation Donation { get; set; }
    }
}
