//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Donation()
        {
            this.DonationCertificates = new HashSet<DonationCertificate>();
        }
    
        public int DonationID { get; set; }
        public string DonationName { get; set; }
        public int DonorID { get; set; }
        public string DonationReference { get; set; }
        public System.Guid GUID { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public Nullable<int> DonationStatusID { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<System.DateTime> FeedbackDate { get; set; }
        public System.DateTime InsertDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<double> Fees { get; set; }
        public Nullable<double> NetAmount { get; set; }
        public string DonatorType { get; set; }
    
        public virtual DonationStatu DonationStatu { get; set; }
        public virtual Donor Donor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonationCertificate> DonationCertificates { get; set; }
        public virtual AspNetStudent AspNetStudent { get; set; }
    }
}
